package com.learning.Project.config;

import com.learning.Project.service.CustomUserDetailsService;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

@Component
public class JwtRequestFilter extends OncePerRequestFilter {

    @Autowired
    private CustomUserDetailsService userDetailsService;

    @Autowired
    private JwtTokenUtil jwtTokenUtil;

    @Autowired
    private StringRedisTemplate redisTemplate;

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain chain)
            throws ServletException, IOException {

        final String requestTokenHeader = request.getHeader("Authorization");

        String username = null;
        String jwtToken = null;

        // JWT Token is in the form "Bearer token". Remove Bearer prefix and get only
        // the Token
        if (requestTokenHeader != null && requestTokenHeader.regionMatches(true, 0, "Bearer ", 0, 7)) {
            jwtToken = requestTokenHeader.substring(7).trim();
            // In case the user pasted "Bearer <token>" into a Swagger UI bearer field,
            // resulting in "Bearer Bearer <token>"
            if (jwtToken.regionMatches(true, 0, "Bearer ", 0, 7)) {
                jwtToken = jwtToken.substring(7).trim();
            }
            try {
                // First check Redis for sliding session expiration
                String sessionKey = "jwt_session:" + jwtToken;
                Boolean hasSession = redisTemplate.hasKey(sessionKey);

                if (Boolean.TRUE.equals(hasSession)) {
                    String tokenBootId = jwtTokenUtil.getBootIdFromToken(jwtToken);
                    if (jwtTokenUtil.getBootId().equals(tokenBootId)) {
                        username = jwtTokenUtil.getUsernameFromToken(jwtToken);
                        // Sliding expiration: user is active, so refresh TTL in Redis
                        redisTemplate.expire(sessionKey, jwtTokenUtil.getValidityDuration());
                        if (username != null) {
                            String activeTokenKey = "user_active_token:" + username;
                            redisTemplate.expire(activeTokenKey, jwtTokenUtil.getValidityDuration());
                        }
                    } else {
                        logger.warn("JWT Boot ID mismatch. Token was generated by a previous application run. Invalidating.");
                        redisTemplate.delete(sessionKey);
                        String usernameFromToken = jwtTokenUtil.getUsernameFromToken(jwtToken);
                        if (usernameFromToken != null) {
                            redisTemplate.delete("user_active_token:" + usernameFromToken);
                        }
                    }
                } else {
                    logger.warn("JWT Session not found in Redis or expired due to inactivity");
                }
            } catch (IllegalArgumentException e) {
                logger.warn("Unable to get JWT Token: " + e.getMessage());
            } catch (io.jsonwebtoken.ExpiredJwtException e) {
                logger.warn("JWT Token has expired: " + e.getMessage());
            } catch (Exception e) {
                logger.error("Error processing JWT Token: " + e.getMessage(), e);
            }
        } else {
            logger.debug("JWT Token does not begin with Bearer String");
        }

        // Once we get the token, validate it and set authentication
        if (username != null && SecurityContextHolder.getContext().getAuthentication() == null) {
            UserDetails userDetails = this.userDetailsService.loadUserByUsername(username);

            // if token is valid configure Spring Security to manually set authentication
            if (jwtTokenUtil.validateToken(jwtToken, userDetails)) {
                UsernamePasswordAuthenticationToken usernamePasswordAuthenticationToken = new UsernamePasswordAuthenticationToken(
                        userDetails, null, userDetails.getAuthorities());
                usernamePasswordAuthenticationToken
                        .setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
                // After setting the Authentication in the context, we specify
                // that the current user is authenticated. So it passes the Spring Security
                // Configurations successfully.
                SecurityContextHolder.getContext().setAuthentication(usernamePasswordAuthenticationToken);
            }
        }
        chain.doFilter(request, response);
    }
}
